# Generated by Django 2.0.6 on 2018-06-16 16:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_match', models.IntegerField()),
                ('win', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=None, to='core.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(choices=[('Protos', 'protos'), ('Zerg', 'zerg'), ('Terran', 'terran')], max_length=12)),
                ('player_type', models.CharField(choices=[('Human', 'human'), ('Random', 'random'), ('Cbl_1', 'cbl_1'), ('Easy', 'easy'), ('Medium', 'medium'), ('Hard', 'hard')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Replay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replay_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='media/'), upload_to='replays/')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=None, to='core.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('New', 'new'), ('Waiting', 'waiting'), ('Done', 'done')], max_length=12)),
                ('max_retries', models.IntegerField()),
                ('last_assigned', models.DateTimeField(blank=True, default=None, null=True)),
                ('match', models.OneToOneField(on_delete=None, to='core.Match')),
                ('replay', models.OneToOneField(on_delete=None, to='core.Replay')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=None, to='core.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Idle', 'idle'), ('Busy', 'busy'), ('Off', 'off')], max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('last_known_ip', models.CharField(max_length=20)),
                ('tasks', models.ManyToManyField(through='core.TaskAssignment', to='core.Task')),
            ],
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='worker',
            field=models.ForeignKey(on_delete=None, to='core.Worker'),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='player',
            field=models.ForeignKey(on_delete=None, to='core.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(through='core.MatchPlayer', to='core.Player'),
        ),
    ]
